// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwhKIQYgxV0BzbY7hRMiYIzE-HV-IsSoU',
    appId: '1:583316137600:web:3e9da241767e3a5c7c2865',
    messagingSenderId: '583316137600',
    projectId: 'crud-fee52',
    authDomain: 'crud-fee52.firebaseapp.com',
    storageBucket: 'crud-fee52.appspot.com',
    measurementId: 'G-0ZZDT72MMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClbPyQkwnG8XaHjbiKck-6KO-V43rXz6Q',
    appId: '1:583316137600:android:bacad80a6f905b3b7c2865',
    messagingSenderId: '583316137600',
    projectId: 'crud-fee52',
    storageBucket: 'crud-fee52.appspot.com',
  );
}
